import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Patrick Collins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/frog-svg.svg" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to PatrickAlphaC!</h1>
        <h2>
          Web3, Smart Contracts, Software Engineering, Solidity, Vyper, and more
        </h2>
        <h3 className="p-6 text-5xl">
          The two best smart contract courses ever released 👇
        </h3>
        <div className={styles.grid}>
          <a
            href="https://www.youtube.com/watch?v=gyMwXuJrbJQ"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Learn Solidity with Javascript &rarr;</h2>
            <Image
              src="/solidity-fcc.png"
              alt="Learn Blockchain, Solidity, and Full Stack Web3 Development with JavaScript – 32-Hour Course"
              width={1280}
              height={720}
            />
          </a>

          <a
            href="https://www.youtube.com/watch?v=M576WGiDBdQ"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Learn Solidity with Python &rarr;</h2>
            <Image
              src="/python-fcc.jpeg"
              alt="Solidity, Blockchain, and Smart Contract Course – Beginner to Expert Python Tutorial"
              width={1280}
              height={720}
            />
          </a>
        </div>
        <h3 className="p-6 text-3xl">
          My YouTube and Medium, where I put all the good stuff. Especially my
          YouTube.
        </h3>
        <div className={styles.grid}>
          <a
            href="https://www.youtube.com/channel/UCn-3f8tw_E1jZvhuHatROwA?view_as=subscriber?sub_confirmations=1"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Subscribe to Patrick's YouTube Channel &rarr;</h2>
            <Image
              src="/frog-svg.svg"
              alt="PatrickAlphaC's YouTube Channel"
              width={1280}
              height={720}
            />
          </a>

          <a
            href="https://medium.com/@patrick.collins_58673"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Medium Articles &rarr;</h2>
            <Image
              src="/patrick-headshot.jpg"
              alt="PatrickAlphaC's Medium Articles"
              width={1000}
              height={717}
            />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://docs.chain.link/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Lover of
          <Image
            src="/chainlink-blue.svg"
            alt="Chainlink Logo"
            width={64}
            height={48}
          />
        </a>
      </footer>
    </div>
  );
};

export default Home;
